# Generated by Django 5.1.7 on 2025-09-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_totp_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='totp_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totp_secret',
        ),
        migrations.AddField(
            model_name='user',
            name='email_2fa_code',
            field=models.CharField(blank=True, help_text='Temporary 2FA code', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='email_2fa_code_expires',
            field=models.DateTimeField(blank=True, help_text='When the 2FA code expires', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_2fa_enabled',
            field=models.BooleanField(default=False, help_text='Whether email 2FA is enabled'),
        ),
    ]
