# Generated by Django 5.1.7 on 2025-09-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_totp_enabled_remove_user_totp_secret_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE accounts_user SET email_2fa_enabled = TRUE WHERE email_2fa_enabled = FALSE;",
            reverse_sql="UPDATE accounts_user SET email_2fa_enabled = FALSE WHERE email_2fa_enabled = TRUE;",
        ),
    ]
