# Generated by Django 5.1.7 on 2025-09-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='drug',
        ),
        migrations.AddField(
            model_name='medication',
            name='drug_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
