# Generated by Django 5.2.5 on 2025-08-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('atc_code', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
