// src/pages/RegisterPatient.jsx
import React, { useState } from 'react';
import API from '../services/api';
import { useNavigate } from 'react-router-dom';

const initialState = {
  full_name: '',
  dob: '',
  gender: '', // "Male" | "Female" | "Other" | "PreferNotToSay"
  phone: '',
  email: '',
  allergies: '',
  past_adverse_reactions: '',
  medical_conditions: '',
  genetic_info: '',
  weight_kg: '',
  height_cm: '',
  blood_type: '', // e.g. "A+", "O-", etc
  emergency_contact: '',
};

const RegisterPatient = () => {
  const [form, setForm] = useState(initialState);
  const [submitting, setSubmitting] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const navigate = useNavigate();

  const onChange = (e) => {
    const { name, value } = e.target;
    setForm((s) => ({ ...s, [name]: value }));
  };

  const toFloatOrNull = (v) => {
    if (v === null || v === undefined) return null;
    const s = String(v).trim();
    if (s === '') return null;
    const n = Number(s);
    return Number.isFinite(n) ? n : null;
  };

  const onSubmit = async (e) => {
    e.preventDefault();
    setSubmitting(true);
    setErrorMsg('');

    try {
      const payload = {
        full_name: form.full_name.trim(),
        dob: form.dob, // YYYY-MM-DD
        gender: form.gender, // use exact strings from model choices
        phone: form.phone.trim(),
        email: form.email.trim(),
        allergies: form.allergies.trim(),
        past_adverse_reactions: form.past_adverse_reactions.trim(),
        medical_conditions: form.medical_conditions.trim(),
        genetic_info: form.genetic_info.trim(),
        weight_kg: toFloatOrNull(form.weight_kg),
        height_cm: toFloatOrNull(form.height_cm),
        blood_type: form.blood_type.trim(),
        emergency_contact: form.emergency_contact.trim(),
        // patient_id:  ⟵ generated by backend; don't send
        // hospital:    ⟵ ideally set server-side from the authenticated user's profile
      };

      await API.post('/patients/', payload);
      navigate('/doctor/patients');
    } catch (err) {
      const data = err?.response?.data;
      const msg =
        typeof data === 'string'
          ? data
          : data?.detail || JSON.stringify(data || 'Failed to create patient', null, 2);
      setErrorMsg(msg);
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="p-8">
      <h2 className="text-3xl font-bold text-gray-800 mb-6">Register New Patient</h2>

      {errorMsg && (
        <div className="mb-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700 whitespace-pre-wrap">
          {errorMsg}
        </div>
      )}

      <form
        onSubmit={onSubmit}
        className="space-y-6 max-w-3xl bg-white p-6 rounded-lg shadow border border-gray-200"
      >
        {/* Core details */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-semibold text-gray-700">Full Name</label>
            <input
              type="text"
              name="full_name"
              required
              value={form.full_name}
              onChange={onChange}
              className="w-full p-3 border border-gray-300 rounded-lg"
              placeholder="e.g. Ama K. Mensah"
            />
          </div>

          <div>
            <label className="block text-sm font-semibold text-gray-700">Date of Birth</label>
            <input
              type="date"
              name="dob"
              required
              value={form.dob}
              onChange={onChange}
              className="w-full p-3 border border-gray-300 rounded-lg"
            />
          </div>

          <div>
            <label className="block text-sm font-semibold text-gray-700">Gender</label>
            <select
              name="gender"
              required
              value={form.gender}
              onChange={onChange}
              className="w-full p-3 border border-gray-300 rounded-lg"
            >
              <option value="">Select</option>
              <option value="Male">Male</option>
              <option value="Female">Female</option>
              <option value="Other">Other</option>
              <option value="PreferNotToSay">Prefer not to say</option>
            </select>
          </div>
        </div>

        {/* Contact */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-semibold text-gray-700">Phone</label>
            <input
              type="tel"
              name="phone"
              value={form.phone}
              onChange={onChange}
              className="w-full p-3 border border-gray-300 rounded-lg"
              placeholder="+233 24 123 4567"
            />
          </div>
          <div>
            <label className="block text-sm font-semibold text-gray-700">Email</label>
            <input
              type="email"
              name="email"
              value={form.email}
              onChange={onChange}
              className="w-full p-3 border border-gray-300 rounded-lg"
              placeholder="patient@example.com"
            />
          </div>
        </div>

        {/* Medical info */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-semibold text-gray-700">Allergies</label>
            <textarea
              name="allergies"
              rows="3"
              value={form.allergies}
              onChange={onChange}
              className="w-full p-3 border border-gray-300 rounded-lg"
              placeholder="e.g. Penicillin, nuts"
            />
          </div>
          <div>
            <label className="block text-sm font-semibold text-gray-700">Past Adverse Reactions</label>
            <textarea
              name="past_adverse_reactions"
              rows="3"
              value={form.past_adverse_reactions}
              onChange={onChange}
              className="w-full p-3 border border-gray-300 rounded-lg"
              placeholder="e.g. Rash after ibuprofen"
            />
          </div>
        </div>

        <div>
          <label className="block text-sm font-semibold text-gray-700">Medical Conditions</label>
          <textarea
            name="medical_conditions"
            rows="3"
            value={form.medical_conditions}
            onChange={onChange}
            className="w-full p-3 border border-gray-300 rounded-lg"
            placeholder="e.g. Hypertension, Type 2 Diabetes"
          />
        </div>

        <div>
          <label className="block text-sm font-semibold text-gray-700">Genetic Info</label>
          <textarea
            name="genetic_info"
            rows="2"
            value={form.genetic_info}
            onChange={onChange}
            className="w-full p-3 border border-gray-300 rounded-lg"
            placeholder="e.g. CYP2D6 poor metabolizer"
          />
        </div>

        {/* Measurements / misc */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label className="block text-sm font-semibold text-gray-700">Weight (kg)</label>
            <input
              type="number"
              step="0.1"
              name="weight_kg"
              value={form.weight_kg}
              onChange={onChange}
              className="w-full p-3 border border-gray-300 rounded-lg"
              placeholder="e.g. 70.5"
            />
          </div>

          <div>
            <label className="block text-sm font-semibold text-gray-700">Height (cm)</label>
            <input
              type="number"
              step="0.1"
              name="height_cm"
              value={form.height_cm}
              onChange={onChange}
              className="w-full p-3 border border-gray-300 rounded-lg"
              placeholder="e.g. 168"
            />
          </div>

          <div>
            <label className="block text-sm font-semibold text-gray-700">Blood Type</label>
            <select
              name="blood_type"
              value={form.blood_type}
              onChange={onChange}
              className="w-full p-3 border border-gray-300 rounded-lg"
            >
              <option value="">Select</option>
              <option value="A+">A+</option>
              <option value="A-">A-</option>
              <option value="B+">B+</option>
              <option value="B-">B-</option>
              <option value="AB+">AB+</option>
              <option value="AB-">AB-</option>
              <option value="O+">O+</option>
              <option value="O-">O-</option>
            </select>
          </div>
        </div>

        <div>
          <label className="block text-sm font-semibold text-gray-700">Emergency Contact</label>
          <input
            type="text"
            name="emergency_contact"
            value={form.emergency_contact}
            onChange={onChange}
            className="w-full p-3 border border-gray-300 rounded-lg"
            placeholder="Name & phone"
          />
        </div>

        <button
          type="submit"
          disabled={submitting || !form.full_name || !form.dob || !form.gender}
          className={`bg-green-600 text-white py-3 px-6 rounded-lg font-semibold ${
            submitting ? 'opacity-60 cursor-not-allowed' : 'hover:bg-green-700'
          }`}
        >
          {submitting ? 'Adding…' : 'Add Patient'}
        </button>
      </form>
    </div>
  );
};

export default RegisterPatient;
