# Generated by Django 5.2.5 on 2025-08-14 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('PreferNotToSay', 'Prefer not to say')], max_length=20)),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('allergies', models.TextField(blank=True)),
                ('past_adverse_reactions', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('genetic_info', models.TextField(blank=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=3)),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.hospital')),
            ],
        ),
    ]
